#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# Copyright(C) 2024 Yogi Hermawan <yogist.xda@gmail.com>.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See http://www.gnu.org/licenses/gpl-2.0.html for more details.

echo "Cleaning..."

find -name "*.ko" | xargs rm 2>/dev/null
find -name "*.o" | xargs rm 2>/dev/null
find -name "*.o.*" | xargs rm 2>/dev/null
find -name "*.order.cmd" | xargs rm 2>/dev/null
find -name "*.mod.cmd" | xargs rm 2>/dev/null
find -name "*.mod" | xargs rm 2>/dev/null
find -name "*.order" | xargs rm 2>/dev/null
find -name "*.cmd" | xargs rm 2>/dev/null
find -name "*.symvers" | xargs rm 2>/dev/null
find -name "*.mod.c" | xargs rm 2>/dev/null
find -name ".tmp_*" | xargs rm -rf 2>/dev/null

echo "Clean finished"
